version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ensitech_ts
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./apps/backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/ensitech_ts
    ports:
      - "3001:3001"

  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001

volumes:
  pgdata:
